Add missing limits.h includes
In file included from accesscontrol.cpp:18:
accesscontrol.h:36:25: error: 'INT_MAX' was not declared in this scope
   36 |         UndefinedUid = -INT_MAX
      |                         ^~~~~~~
accesscontrol.h:22:1: note: 'INT_MAX' is defined in header '<climits>'; did you forget to '#include <climits>'?
   21 | #include <QObject>
  +++ |+#include <climits>
   22 |

In file included from accesscontrol.cpp:19:
accesscontrol.cpp: In member function 'int Sailfish::AccessControl::systemUserUid()':
/nix/store/0y2nm95lc1nk71k69668fk3mj1gczfpx-sailfish-access-control-0.0.11-dev/include/sailfishaccesscontrol/sailfishaccesscontrol.h:25:32: error: 'UINT_MAX' was not declared in this scope
   25 | #define SAILFISH_UNDEFINED_UID UINT_MAX
      |                                ^~~~~~~~
accesscontrol.cpp:54:16: note: in expansion of macro 'SAILFISH_UNDEFINED_UID'
   54 |     if (uid == SAILFISH_UNDEFINED_UID)
      |                ^~~~~~~~~~~~~~~~~~~~~~
accesscontrol.cpp:20:1: note: 'UINT_MAX' is defined in header '<climits>'; did you forget to '#include <climits>'?
   19 | #include "sailfishaccesscontrol.h"
  +++ |+#include <climits>
   20 |